### PR TITLE
Event participation

### PR DESCRIPTION
**Pull request by aliraiki**
- Change the event model so it can include the event owner
- Add a "participate" button
- Add a "leave event" button
- Add a counter to display the number of seats available
- Implement possibility for the event owner to export participant list to excel

### CODE REVIEW

**Comment by elyasha** [comment]
I only have some questions:
1. why create the give_user method that only gives the user ? [views.py]
2. why delete the category field in the user registration form ? [forms.py]
@PrissVI

**Review by elyasha — COMMENTED** [review]
Good job, I only have the questions that i sent you. @PrissVI

**Comment by aliraiki** [comment]
1. I forgot to remove the give_user method, sorry
2. The user can only choose one category, so no need to specify the field on the forms.py : Before removing the line from the file, the field was displayed the same way as structure, and I just changed it so it can be displayed like membership type.
@elyasha

**Comment by elyasha** [comment]
@PrissVi I did the merge with the rebase of the last modifications to get the CI working!

**Pull request closed without merging**
