### PR TITLE
Refactor navbar

### PR DESCRIPTION
**Pull request by aliraiki**
Changed the composition of the navbar, and removed some css attributes that disturbed it

### CODE REVIEW

**Comment by elyasha** [comment]
Hello, i do not think that the changes to the event and yearbook were good. Actually they were good before. The rest are really interesting, could you send another PR ? Try to do a rebase with dev @PrissVI

**Comment by aliraiki** [comment]
Why don’t you think they are good ? I think it’s pretty ergonomic to have "Create event" and "Event list" in the dropdown @elyasha

**Comment by elyasha** [comment]
We can add "create event" in the dropdown, but in the way that you did, the page events/ is no longer used. I believe that we can leave it in order to have something to redirect users to other pages! For the yearbook I believe we can leave the button to go for the user's profile because it is always interesting to have more than 1 option to go to user's profile! What do you think ? @PrissVI

**Comment by aliraiki** [comment]
For the page /events, I thought it didn’t look too good because they were too many buttons but we can leave it since we already have it. But for the user’s profile button I really don’t think it’s necessary, it looks like we forgot we already had a profile button and added one by mistake. I will change my PR as soon as possible to revert the Event dropdown, thanks for the feedback ! @elyasha

**Comment by aliraiki** [comment]
I changed it back, you can merge it whenever you want :) @elyasha

**Review by elyasha — APPROVED** [review]
Good job !

**Pull request merged**
